# Auto-generated by appkit-tools

# 设置C++标准
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS ON)

# 设置平台相关变量
set(APPKIT_PLATFORM "STM32")
set(APPKIT_OSAL_SYSTEM "FREERTOS")

# 定义AppKit根目录
set(APPKIT_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Middlewares/Third_Party/appkit")

# 包含AppKit子模块
add_subdirectory("${APPKIT_ROOT_DIR}" EXCLUDE_FROM_ALL)

# 将AppKit集成到项目中
target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${APPKIT_SOURCE_FILES})
target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE ${APPKIT_INCLUDE_DIRS})
target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE ${THIRD_PARTY_LIBRARIES})

# 导入宏定义
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/private/ProjectConfig.cmake)

# 定义文件名宏
include(${APPKIT_ROOT_DIR}/cmake/define_file_name.cmake)
redefine_file_macro(${CMAKE_PROJECT_NAME})
